---
title: Your awesome title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  uploads:
    title: Uploads
    output: true
subtitle: Your awesome subtitle
description: This is the demo site for a Jekyll theme version of HTML5 UP's sleek,
  responsive site template Prologue.
author: Your Incredible Name
email: your-email@example.com
avatar: assets/images/avatar.jpg
baseurl: ''
url: https://tacus.github.io
twitter_url: 
facebook_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
github_url: 
pinterest_url: 
slack_url: 
dribbble_url: 
google_analytics: 
remote_theme: chrisbobbe/jekyll-theme-prologue
